export const enum ActionsHotelType {
	SEARCH_HOTELS_LIST = "SEARCH_HOTELS_LIST",
	SEARCH_HOTELS_LIST_SUCCESS = "SEARCH_HOTELS_LIST_SUCCESS",
	SEARCH_HOTELS_LIST_ERROR = "SEARCH_HOTELS_LIST_ERROR"
}

export const enum GuestCapacity {
	INCREASE_ADULTS_CAPACITY = "INCREASE_ADULTS_CAPACITY",
	DECREASE_ADULTS_CAPACITY = "DECREASE_ADULTS_CAPACITY",
	INCREASE_CHILDREN_CAPACITY = "INCREASE_CHILDREN_CAPACITY",
	DECREASE_CHILDREN_CAPACITY = "DECREASE_CHILDREN_CAPACITY"
}

export const enum ActionRoomsType {
	GET_ROOMS_LIST = "GET_ROOMS_LIST",
	GET_ROOMS_LIST_SUCCESS = "GET_ROOMS_LIST_SUCCESS",
	GET_ROOMS_LIST_ERROR = "GET_ROOMS_LIST_ERROR"
}
